### PR TITLE
fix: avoid Cannot read property 'errorName' of null

### PR DESCRIPTION
**Pull request by assaulter**
**What are you adding/fixing?**

NgErrorsDirective.subject is BehaviourSubject and initial value is null.
So there is a time to access nullObject at NgErrorDirective.

**Have you added tests for your changes?**

No

**Will this need documentation changes?**

No

**Does this introduce a breaking change?**

No

**Other information**

### CODE REVIEW

**Comment by toddmotto** [comment]
Can you provide your code to reproduce this so I can take a look ?

**Comment by assaulter** [comment]
I am sorry for lack of explanation.
I create formGroup with initialValue like this.

```sample.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-sample',
  templateUrl: './sample.component.html',
  styleUrls: ['./sample.component.css']
})
export class SampleComponent {
  form: FormGroup;

  constructor(
    private fb: FormBuilder
  ) {
    this.form = this.fb.group({
      name: ['initialvalue', Validators.required]
    })
  }
}
```

and template

```sample.component.html
<form [formGroup]="form">
  <input formControlName="name">
  <!--use ngxerrors-->
  <div ngxErrors="name">
    <div ngxError="required">
      required!!
    </div>
  </div>
</form>
```

I run this code, and i got "ERROR TypeError: Cannot read property 'errorName' of null" at chrome console.

In this situation,
https://github.com/UltimateAngular/ngxerrors/blob/master/src/ngxerrors.directive.ts#L38
checkStatus function is return and do nothing. but
https://github.com/UltimateAngular/ngxerrors/blob/master/src/ngxerror.directive.ts#L58
depending on the function of behaviourSubject, obj is null.

**Comment by rynclark** [comment]
Thanks for the PR - we've just released 1.0.0 which actually puts this check in so it solves the issue!

**Comment by assaulter** [comment]
I see! thank you!

**Pull request closed without merging**
